server:
  port: 8081

spring:
    application:
        name: account-microservice
    data:
        mongodb:
            host: db_mongo
            port: 27017
            database: BankAccount

eureka:
    client:
        serviceUrl:
            defaultZone: http://api-discovery:9999/eureka/